components:
  schemas:
    ProductInput:
      type: object
      required:
        - name
        - price
      properties:
        name:
          type: string
          description: Product name
        price:
          type: number
          description: Product price
        description:
          type: string
          description: Optional product description
        category:
          type: string
          description: Product category
        stock:
          type: integer
          description: Available stock

    ProductResponse:
      type: object
      properties:
        productId:
          type: string
          description: Unique identifier for the product
        name:
          type: string
          description: Product name
        price:
          type: number
          description: Product price
        description:
          type: string
          description: Product description
        category:
          type: string
          description: Product category
        stock:
          type: integer
          description: Available stock
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the product was created
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when the product was last updated
